eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Replace with your Eureka server URL
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF
